name: Laravel CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.8'
          extensions: mbstring, dom, curl, libxml, pdo_mysql
          key: ${{ secrets.COMPOSER_AUTH }}
          
      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Key
        run: php artisan key:generate

      - name: Run Migrations & Seeders
        run: php artisan migrate --seed

      - name: Execute Tests (Optional)
        run: vendor/bin/phpunit

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Production Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/your/laravel/project
            git pull origin main
            composer install --no-dev --prefer-dist --no-progress --no-interaction
            php artisan migrate --force
            php artisan optimize
